### ISSUE TITLE
Cannot run commands through console

### ISSUE THREAD

**Issue by Teslicek** [Euphillya/WorldEdit-Folia#5]
### WorldEdit Version

.

### Platform Version

Folia-1.21.1

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Self-explanatory. 

The console is unable to run commands, but if a player runs them, its fine.

```
[16:17:53 INFO]: Region selected as cuboid
[16:17:55 ERROR]: An unexpected error while handling a WorldEdit command
java.lang.NullPointerException: Cannot read field "capturedTileEntities" because the return value of "net.minecraft.server.level.ServerLevel.getCurrentWorldData()" is null
        at net.minecraft.world.level.chunk.LevelChunk.getBlockEntity(LevelChunk.java:464) ~[folia-1.21.1.jar:1.21.1-DEV-2e7bc07]
        at net.minecraft.world.level.chunk.LevelChunk.getBlockEntity(LevelChunk.java:458) ~[folia-1.21.1.jar:1.21.1-DEV-2e7bc07]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.bukkit.adapter.impl.v1_21.PaperweightAdapter.getFullBlock(PaperweightAdapter.java:396) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.bukkit.BukkitWorld.getFullBlock(BukkitWorld.java:508) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.extent.AbstractDelegateExtent.getFullBlock(AbstractDelegateExtent.java:73) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.extent.AbstractDelegateExtent.getFullBlock(AbstractDelegateExtent.java:73) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.extent.world.WatchdogTickingExtent.getFullBlock(WatchdogTickingExtent.java:108) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.extent.AbstractDelegateExtent.getFullBlock(AbstractDelegateExtent.java:73) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.extent.AbstractDelegateExtent.getFullBlock(AbstractDelegateExtent.java:73) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.extent.AbstractDelegateExtent.getFullBlock(AbstractDelegateExtent.java:73) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.extent.AbstractDelegateExtent.getFullBlock(AbstractDelegateExtent.java:73) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.extent.cache.LastAccessExtentCache.getFullBlock(LastAccessExtentCache.java:68) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.extent.AbstractDelegateExtent.getFullBlock(AbstractDelegateExtent.java:73) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.extent.AbstractDelegateExtent.getFullBlock(AbstractDelegateExtent.java:73) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.extent.AbstractDelegateExtent.getFullBlock(AbstractDelegateExtent.java:73) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.extent.AbstractBufferingExtent.getFullBlock(AbstractBufferingExtent.java:68) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.extent.AbstractDelegateExtent.getFullBlock(AbstractDelegateExtent.java:73) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.extent.AbstractBufferingExtent.getFullBlock(AbstractBufferingExtent.java:68) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.extent.AbstractDelegateExtent.getFullBlock(AbstractDelegateExtent.java:73) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.extent.AbstractBufferingExtent.getFullBlock(AbstractBufferingExtent.java:68) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.extent.AbstractDelegateExtent.getFullBlock(AbstractDelegateExtent.java:73) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.extent.world.WatchdogTickingExtent.getFullBlock(WatchdogTickingExtent.java:108) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.extent.AbstractDelegateExtent.getFullBlock(AbstractDelegateExtent.java:73) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.extent.ChangeSetExtent.setBlock(ChangeSetExtent.java:97) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.extent.MaskingExtent.setBlock(MaskingExtent.java:69) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.extent.validation.BlockChangeLimiter.setBlock(BlockChangeLimiter.java:88) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.extent.validation.DataValidatorExtent.setBlock(DataValidatorExtent.java:77) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.EditSession.setBlock(EditSession.java:764) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.EditSession.setBlock(EditSession.java:804) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.function.block.BlockReplace.apply(BlockReplace.java:53) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.function.visitor.RegionVisitor.resume(RegionVisitor.java:60) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:74) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.command.RegionCommands.set(RegionCommands.java:111) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_set(RegionCommandsRegistration.java:454) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:507) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:391) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar/com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[worldedit-bukkit-7.3.10-SNAPSHOT-dist.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:1044) ~[folia-1.21.1.jar:1.21.1-DEV-2e7bc07]
        at org.bukkit.craftbukkit.CraftServer.dispatchServerCommand(CraftServer.java:995) ~[folia-1.21.1.jar:1.21.1-DEV-2e7bc07]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:526) ~[folia-1.21.1.jar:1.21.1-DEV-2e7bc07]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:296) ~[folia-1.21.1.jar:1.21.1-DEV-2e7bc07]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148) ~[folia-1.21.1.jar:1.21.1-DEV-2e7bc07]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:418) ~[folia-1.21.1.jar:1.21.1-DEV-2e7bc07]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:540) ~[folia-1.21.1.jar:1.21.1-DEV-2e7bc07]
        at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?]
[16:17:55 INFO]: Please report this error: [See console]
[16:17:55 INFO]: java.lang.NullPointerException: Cannot read field "capturedTileEntities" because the return value of "net.minecraft.server.level.ServerLevel.getCurrentWorldData()" is null
```

### Expected Behavior

No error.

### Reproduction Steps

Select a region and use "//set 0" from console.

**Comment by Euphillya** [comment]
I will check tomorrow

**Comment by Euphillya** [comment]
@Teslicek Can you try this build : https://github.com/Euphillya/WorldEdit-Folia/actions/runs/12154225061

**Comment by Lioncat6** [comment]
Can confirm, this is still an issue. On the latest version from the actions, you get a null pointer exception from console `[17:54:48 ERROR]: An unexpected error while handling a WorldEdit command
java.lang.NullPointerException: null`. From the version above ^, I get `[18:11:11 INFO]: Editing on unsupported versions is disabled.` . No other errors, though

**Comment by Euphillya** [comment]
can not be fixed
